version: "2.4"
services:
  cron:
    build: .
    env_file: 
      - ./sync.env
    volumes:
      - ./register:/usr/src/register
      - ./notificationsJSON:/usr/src/notificationsJSON
      - ./var/log/sync:/var/log/sync
      - ./cron/root:/etc/cron.d/root
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
